sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=fiwoo/eureka-registry-service
    - MICROSERVICE="eureka-registry-service"
    - TOMCAT_VERSION=8.5.27

script:
  - docker build -t $DOCKER_IMAGE infrastructure/docker-containers/ubuntu_16.04-tomcat/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push $DOCKER_IMAGE:latest;
      docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;

      set -x;
      LOWCASE_MICROSERVICE=$(echo $MICROSERVICE | tr '[:upper:]' '[:lower:]');
      docker build -t fiwoo/$LOWCASE_MICROSERVICE:latest .;
      docker tag fiwoo/$LOWCASE_MICROSERVICE:latest fiwoo/$LOWCASE_MICROSERVICE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push fiwoo/$LOWCASE_MICROSERVICE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push fiwoo/$LOWCASE_MICROSERVICE:latest;
    fi

notifications:
  email:
    recipients:
      - emergya-integration-github@emergya.com
    on_success: always
    on_failure: always
