server:
  port: 3331
spring:
  application:
    name: s4c-microservice-eureka-registry-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
